name: CI/CD Pipeline

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  CREATE_AND_RUN_DOCKER_IMAGE:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t automatrix/selenium-test:latest -f Dockerfile .
          docker run -d --name selenium-container automatrix/selenium-test:latest

  RUN_SELENIUM_TEST:
    needs: CREATE_AND_RUN_DOCKER_IMAGE
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chrome, firefox ]
        remote_run: [ selenium_hub, browser_stack ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull automatrix/selenium-test:latest
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Environment Variables
        run: |
          echo "BROWSER=${{ matrix.browser }}" >> $GITHUB_ENV
          echo "REMOTE_RUN=${{ matrix.remote_run }}" >> $GITHUB_ENV
        env:
          BROWSER: ${{ matrix.browser }}
          REMOTE_RUN: ${{ matrix.remote_run }}

      - name: Run Selenium tests
        run: |
          docker run --network container:selenium-container automatrix/selenium-test:latest java -cp "/path/to/your/testng.xml:/path/to/your/classes/*" org.testng.TestNG /path/to/your/testng.xml --browser $BROWSER --remote_run $REMOTE_RUN
