name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for Selenium tests (chrome or firefox)'
        required: true
        default: 'chrome'
    branches:
      - master

jobs:
  CREATE_AND_RUN_DOCKER_IMAGE:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          drivers: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t amaurya1702/selenium-test:latest -f Dockerfile .
          docker run -d --name selenium-container amaurya1702/selenium-test:latest

      - name: Push Docker image to Docker Hub
        run: docker push amaurya1702/selenium-test:latest

  RUN_SELENIUM_TEST:
    needs: CREATE_AND_RUN_DOCKER_IMAGE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          drivers: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull amaurya1702/selenium-test:latest

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          architecture: 'x64'



      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: /usr/share/maven
          key: maven-${{ runner.os }}-${{ hashFiles('**/usr/share/maven/**') }}

      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Start Selenium Grid Hub and Nodes
        run: |
          docker run -d -p 4444:4444 --name selenium-hub selenium/hub:latest
          docker run -d --link selenium-hub:hub --name selenium-node-chrome selenium/node-chrome:latest
          docker run -d --link selenium-hub:hub --name selenium-node-firefox selenium/node-firefox:latest

      - name: Validate Browser Input
        run: |
          if [ "${{ github.event.inputs.browser }}" != "chrome" ] && [ "${{ github.event.inputs.browser }}" != "firefox" ]; then
            echo "Invalid browser option. Supported options are: chrome, firefox."
            exit 1
          fi

      - name: Set up Maven settings.xml
        run: cp ./.github/settings/settings.xml $HOME/.m2/settings.xml

      - name: Clean and Build
        run: |
          mvn clean

      - name: Run Test, Generate Allure Report
        run: |
          mvn test -s $HOME/.m2/settings.xml allure:report \
          -DseleniumGridURL=http://localhost:4444 \
          -Dbrowser=${{ github.event.inputs.browser }}
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}